from assets import Assets


TILE_SIZE = 32
MOB_VISION_RANGE = 10 * TILE_SIZE
MOBS_SPEED = 2
PLAYER_SPEED = 10
SHOW_INTRO = False
ZOOM_SCALE = 2


COLLISION_RADIUS = 2 * TILE_SIZE
NUM_MOBS = 300
MOB_SPAWN_DOT_X = 100, 100
MOB_SPAWN_DOT_Y = 100, 100

global_assets = Assets()
