from assets import Assets


TILE_SIZE = 32
MOB_VISION_RANGE = 10 * TILE_SIZE
MOBS_SPEED = 2
PLAYER_SPEED = 3
SHOW_INTRO = False
ZOOM_SCALE = 3
MOB_BITE_DAMAGE = 10

COLLISION_RADIUS = 2 * TILE_SIZE
NUM_MOBS = 2
MOB_SPAWN_DOT_X = 100, 100
MOB_SPAWN_DOT_Y = 100, 100


BULLET_SPEED = 10

LIGHT_RADIUS_PX = 15
SOFT_EDGES = True
OVERLAY_ALPHA = 190
global_assets = Assets()
